// Generated by cbindgen — DO NOT EDIT.
//
// C ABI for the voxrt_wake_word SDK package. Always-on keyword
// spotter built on the VoxRT runtime. Re-run via
// `cargo build -p voxrt_wake_word` to regenerate.

#ifndef VOXRT_WAKE_WORD_H
#define VOXRT_WAKE_WORD_H

#include <stdarg.h>
#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>
#include <stdlib.h>
#include <stddef.h>
#include <stdint.h>

#define N_MELS 64

#define N_CHANNELS 64

#define N_BLOCKS 8

#define KERNEL 13

#define BOTTLENECK_DIM 16

/*
 Opaque session handle. Created by `_create`, destroyed by
 `_destroy`. Renamed to `voxrt_wake_word_t` in the generated header.
 */
typedef struct voxrt_wake_word_t voxrt_wake_word_t;

/*
 Status returned by every `voxrt_wake_word_*` function. `VOXRT_OK`
 is `0`; each error class is a stable negative value.
 */
typedef int32_t voxrt_status_t;

/*
 One detection event written into the caller-owned array passed to
 `_push_pcm_*`. `#[repr(C)]` for stable layout across the FFI.
 */
typedef struct {
  /*
   0-based frame index since session start (or last `_reset`).
   */
  uint64_t frame_index;
  /*
   Seconds since session start at the detection frame's start.
   */
  float timestamp_sec;
  /*
   Sigmoid score in `[0, 1]`.
   */
  float score;
} voxrt_wake_word_detection_t;

#define VOXRT_OK 0

/*
 Invalid argument (null pointer where one was required, value
 outside the supported range, mismatched length).
 */
#define VOXRT_ERR_INVALID_ARG -1

/*
 Handle is null or already destroyed.
 */
#define VOXRT_ERR_INVALID_HANDLE -2

/*
 `.vxrt` bytes failed to deserialise (magic / header / decrypt /
 JSON manifest parse).
 */
#define VOXRT_ERR_MODEL_DESERIALIZE -3

/*
 `.vxrt` deserialised but the topology doesn't match what the
 wake-word loader expects (missing tensor, wrong shape).
 */
#define VOXRT_ERR_MODEL_SHAPE -4

/*
 Allocation failure.
 */
#define VOXRT_ERR_OOM -6

/*
 Caller's detection buffer can't hold every emitted detection.
 `*out_detections_written` carries the required slot count.
 */
#define VOXRT_ERR_BUFFER_TOO_SMALL -7

/*
 Unexpected internal state — should never happen in shipping builds.
 */
#define VOXRT_ERR_INTERNAL -100

#ifdef __cplusplus
extern "C" {
#endif // __cplusplus

/*
 `(major << 16) | minor`. Bump major on breaking changes; minor on
 backward-compatible additions. `(1, 0)` for the M4/8 first ship.
 */
uint32_t voxrt_wake_word_abi_version(void);

/*
 NUL-terminated SDK version string (compile-time `CARGO_PKG_VERSION`).
 Pointer is `'static` — caller MUST NOT free.
 */
const char *voxrt_wake_word_version(void);

/*
 Construct a session from `.vxrt v2` bytes. On success writes the
 handle into `*out_handle` and returns [`VOXRT_OK`]; on failure
 `*out_handle` is left untouched (callers should null-init it).

 Defaults to `threshold=0.5`, `cooldown_frames=100`, `window_size=200`.
 Adjust at runtime via `_set_threshold` / `_set_cooldown_frames`.
 */
voxrt_status_t voxrt_wake_word_create(const uint8_t *model_bytes,
                                      size_t model_len,
                                      voxrt_wake_word_t **out_handle);

/*
 Reclaim a session handle. Idempotent on null. After this call the
 handle MUST NOT be used.
 */
void voxrt_wake_word_destroy(voxrt_wake_word_t *handle);

/*
 Wipe accumulated state (FIFO buffers, pre-emph carry, rolling
 pool, cooldown, frame counter). Subsequent pushes behave as if
 from a fresh session.
 */
voxrt_status_t voxrt_wake_word_reset(voxrt_wake_word_t *handle);

/*
 Set the sigmoid-space detection threshold (range `[0, 1]`).
 */
voxrt_status_t voxrt_wake_word_set_threshold(voxrt_wake_word_t *handle, float threshold);

/*
 Set the post-detection cooldown in frames (1 frame = 10 ms).
 */
voxrt_status_t voxrt_wake_word_set_cooldown_frames(voxrt_wake_word_t *handle,
                                                   size_t cooldown_frames);

/*
 Push a chunk of i16 PCM (mono, 16 kHz, native-endian) into the
 session and report any detections that crossed threshold.

 - `pcm` / `pcm_len`: input samples.
 - `out_detections` / `out_detections_cap`: caller-owned array; up
   to `out_detections_cap` events are written. Pass null + cap=0 if
   the consumer only watches `current_score`.
 - `*out_detections_written`: count of events emitted on success
   (≤ cap), OR the count NEEDED if buffer was too small.
 */
voxrt_status_t voxrt_wake_word_push_pcm_i16(voxrt_wake_word_t *handle,
                                            const int16_t *pcm,
                                            size_t pcm_len,
                                            voxrt_wake_word_detection_t *out_detections,
                                            size_t out_detections_cap,
                                            size_t *out_detections_written);

/*
 Push f32 PCM (range `[-1, 1]`, mono, 16 kHz). Otherwise identical
 to [`voxrt_wake_word_push_pcm_i16`].
 */
voxrt_status_t voxrt_wake_word_push_pcm_f32(voxrt_wake_word_t *handle,
                                            const float *pcm,
                                            size_t pcm_len,
                                            voxrt_wake_word_detection_t *out_detections,
                                            size_t out_detections_cap,
                                            size_t *out_detections_written);

/*
 Latest sigmoid score (0..1). 0.5 before any frame has been emitted.
 */
voxrt_status_t voxrt_wake_word_current_score(voxrt_wake_word_t *handle, float *out_score);

#ifdef __cplusplus
}  // extern "C"
#endif  // __cplusplus

#endif  /* VOXRT_WAKE_WORD_H */
